import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedVector3Widget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedDontstopkeepuptheworkWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedImage1Widget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedMathWidget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedTheansweriswrongWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedVector4Widget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect2widget/generated/GeneratedSuper_SkillsTransparent3Widget6.dart';

/* Frame Math correct 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMathcorrect2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedMath3Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,

              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 254, 225, 85),
                  ),
                ),
                Positioned(
                  left: 27.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 104.0,
                  child: GeneratedSuper_SkillsTransparent3Widget6(),
                ),
                Positioned(
                  left: 22.0,
                  top: 144.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector3Widget8(),
                ),
                Positioned(
                  left: 22.0,
                  top: 572.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector4Widget5(),
                ),
                Positioned(
                  left: 297.0,
                  top: 629.0,
                  right: null,
                  bottom: null,
                  width: 28.0,
                  height: 28.0,
                  child: GeneratedImage1Widget8(),
                ),
                Positioned(
                  left: 70.0,
                  top: 59.0,
                  right: null,
                  bottom: null,
                  width: 362.0,
                  height: 69.0,
                  child: GeneratedMathWidget6(),
                ),
                Positioned(
                  left: 10.0,
                  top: 223.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedTheansweriswrongWidget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 343.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedDontstopkeepuptheworkWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
