import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedApple012Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedSuper_SkillsTransparent3Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedloginpagewidget/generated/GeneratedDownicon1Widget1.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 400.0,
        height: 850.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -35.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 552.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 540.75738525390625,
                right: null,
                bottom: null,
                width: 366.6650085449219,
                height: 308.35704040527344,
                child: GeneratedDownicon1Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 65.0,
                child: GeneratedFrameWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 65.0,
                child: GeneratedFrameWidget1(),
              ),
              Positioned(
                left: 12.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -220.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1027777777777778;

                  final double height = constraints.maxHeight * 0.0559375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1127777777777778,
                        y: constraints.maxHeight * 0.588875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedApple012Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 75.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 234.0,
                child: GeneratedSuper_SkillsTransparent3Widget(),
              )
            ]),
      ),
    ));
  }
}
