import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedSuper_SkillsTransparent4Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedMobileNavItemWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedMobileNavItemWidget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedMedalgamesvgrepocom1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedAvatarWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedVector3Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedLevel32Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedMobileNavItemWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedHamburgerMenuWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedUser2395Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmainpagewidget/generated/GeneratedTrophysvgrepocom1Widget.dart';

/* Frame Main Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 299.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 32.842105865478516,
                height: 24.0,
                child: GeneratedHamburgerMenuWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 85.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 119.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -121.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget2()),
              ),
              Positioned(
                left: 300.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedTrophysvgrepocom1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedMedalgamesvgrepocom1Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 150.0,
                child: GeneratedFrameWidget2(),
              ),
              Positioned(
                left: 287.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 158.0,
                child: GeneratedAvatarWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedUser2395Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 66.0,
                child: GeneratedLevel32Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent4Widget(),
              )
            ]),
      ),
    ));
  }
}
