import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedMobileNavItemWidget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedMedalgamesvgrepocom1Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedFrameWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedMobileNavItemWidget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedTrophysvgrepocom1Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedAchievmentsWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedFrameWidget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedMobileNavItemWidget7.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedSuper_SkillsTransparent4Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedVector3Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget2/generated/GeneratedFrameWidget4.dart';

/* Frame Leaderboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeaderboardWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 85.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget6()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 119.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget7()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -121.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget8()),
              ),
              Positioned(
                left: 300.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedTrophysvgrepocom1Widget2(),
              ),
              Positioned(
                left: 50.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedMedalgamesvgrepocom1Widget2(),
              ),
              Positioned(
                left: 287.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 12.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent4Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 69.0,
                child: GeneratedAchievmentsWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 93.0,
                child: GeneratedFrameWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 93.0,
                child: GeneratedFrameWidget4(),
              ),
              Positioned(
                left: 25.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 93.0,
                child: GeneratedFrameWidget5(),
              )
            ]),
      ),
    ));
  }
}
