import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedHousesvgrepocom11Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedFrameWidget18.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedYougot24Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedGobacktothehomepageandstartagainWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedMathWidget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedVector4Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedImage1Widget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedVector3Widget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect5widget/generated/GeneratedSuper_SkillsTransparent3Widget8.dart';

/* Frame Math correct 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMathcorrect5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget8(),
              ),
              Positioned(
                left: 22.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget10(),
              ),
              Positioned(
                left: 22.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget7(),
              ),
              Positioned(
                left: 297.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget10(),
              ),
              Positioned(
                left: 80.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 69.0,
                child: GeneratedMathWidget8(),
              ),
              Positioned(
                left: 10.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 144.0,
                child: GeneratedYougot24Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 144.0,
                child: GeneratedGobacktothehomepageandstartagainWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 150.0,
                child: GeneratedFrameWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2411111111111111;

                  final double height = constraints.maxHeight * 0.1265625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.38,
                        y: constraints.maxHeight * 0.57,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHousesvgrepocom11Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
