import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedsplashpagewidget/generated/GeneratedSylvainsarrailhcherry1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedsplashpagewidget/generated/GeneratedSuperskills_logo_white1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedsplashpagewidget/generated/GeneratedBackground1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedsplashpagewidget/generated/GeneratedSylvainsarrailhcherry21Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedsplashpagewidget/generated/GeneratedDownicon1Widget.dart';

/* Frame Splash page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginPageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 380.0,
          height: 850.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 217, 217, 217),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 400.0,
                  height: 850.0,
                  child: GeneratedBackground1Widget(),
                ),
                Positioned(
                  left: -129.0,
                  top: -48.0,
                  right: null,
                  bottom: null,
                  width: 605.0,
                  height: 695.0,
                  child: GeneratedSylvainsarrailhcherry1Widget(),
                ),
                Positioned(
                  left: -131.0,
                  top: -219.0,
                  right: null,
                  bottom: null,
                  width: 522.0,
                  height: 759.0,
                  child: GeneratedSylvainsarrailhcherry21Widget(),
                ),
                Positioned(
                  left: 51.37255859375,
                  top: 370.210205078125,
                  right: null,
                  bottom: null,
                  width: 358.18463134765625,
                  height: 485.1774597167969,
                  child: GeneratedDownicon1Widget(),
                ),
                Positioned(
                  left: 55.0,
                  top: 80,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 280.0,
                  child: GeneratedSuperskills_logo_white1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
