import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedImage1Widget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedGoodjobWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedCorrectsignalsvgrepocom1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedTheansweriscorrectWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedSuper_SkillsTransparent3Widget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedVector3Widget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedMathWidget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect1widget/generated/GeneratedVector4Widget3.dart';

/* Frame Math correct 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMathcorrect1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedMath2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,

              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 254, 225, 85),
                  ),
                ),
                Positioned(
                  left: 27.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 104.0,
                  child: GeneratedSuper_SkillsTransparent3Widget4(),
                ),
                Positioned(
                  left: 22.0,
                  top: 144.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector3Widget6(),
                ),
                Positioned(
                  left: 22.0,
                  top: 572.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector4Widget3(),
                ),
                Positioned(
                  left: 297.0,
                  top: 629.0,
                  right: null,
                  bottom: null,
                  width: 28.0,
                  height: 28.0,
                  child: GeneratedImage1Widget6(),
                ),
                Positioned(
                  left: 70.0,
                  top: 59.0,
                  right: null,
                  bottom: null,
                  width: 362.0,
                  height: 69.0,
                  child: GeneratedMathWidget4(),
                ),
                Positioned(
                  left: 10.0,
                  top: 193.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedTheansweriscorrectWidget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 313.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedGoodjobWidget(),
                ),
                Positioned(
                  left: 125.0,
                  top: 403.0,
                  right: null,
                  bottom: null,
                  width: 137.0,
                  height: 137.0,
                  child: GeneratedCorrectsignalsvgrepocom1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
