import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedFrameWidget15.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedVector3Widget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedFrameWidget17.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedSuper_SkillsTransparent3Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedFrameWidget16.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedFrameWidget14.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedHowmuchis42Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedVector4Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedImage1Widget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath3widget/generated/GeneratedMathWidget3.dart';

/* Frame Math 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMath3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget3(),
              ),
              Positioned(
                left: 22.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget5(),
              ),
              Positioned(
                left: 22.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget14(),
              ),
              Positioned(
                left: 195.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget15(),
              ),
              Positioned(
                left: 31.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget16(),
              ),
              Positioned(
                left: 195.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget17(),
              ),
              Positioned(
                left: 297.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget5(),
              ),
              Positioned(
                left: 70.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 69.0,
                child: GeneratedMathWidget3(),
              ),
              Positioned(
                left: 11.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedHowmuchis42Widget(),
              )
            ]),
      ),
    ));
  }
}
