import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedImage1Widget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedHowmuchis22Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedMathWidget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedSuper_SkillsTransparent3Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedVector4Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedFrameWidget13.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedFrameWidget11.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedFrameWidget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedFrameWidget12.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathwidget1/generated/GeneratedVector3Widget4.dart';

/* Frame Math
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMathWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget2(),
              ),
              Positioned(
                left: 12.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget4(),
              ),
              Positioned(
                left: 12.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget10(),
              ),
              Positioned(
                left: 185.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget11(),
              ),
              Positioned(
                left: 21.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget12(),
              ),
              Positioned(
                left: 185.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget13(),
              ),
              Positioned(
                left: 287.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget4(),
              ),
              Positioned(
                left: 60.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 69.0,
                child: GeneratedMathWidget2(),
              ),
              Positioned(
                left: -11.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedHowmuchis22Widget(),
              )
            ]),
      ),
    ));
  }
}
