import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedFrameWidget19.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedPressthecorrectnumber4Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedMathWidget9.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedVector4Widget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedImage1Widget11.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedSuper_SkillsTransparent3Widget9.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedFrameWidget21.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedFrameWidget20.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedVector3Widget11.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath4widget/generated/GeneratedFrameWidget22.dart';

/* Frame Math 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMath4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget9(),
              ),
              Positioned(
                left: 22.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget11(),
              ),
              Positioned(
                left: 22.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget8(),
              ),
              Positioned(
                left: 31.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget19(),
              ),
              Positioned(
                left: 195.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget20(),
              ),
              Positioned(
                left: 31.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget21(),
              ),
              Positioned(
                left: 195.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget22(),
              ),
              Positioned(
                left: 297.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget11(),
              ),
              Positioned(
                left: 70.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 69.0,
                child: GeneratedMathWidget9(),
              ),
              Positioned(
                left: 11.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 117.0,
                child: GeneratedPressthecorrectnumber4Widget(),
              )
            ]),
      ),
    ));
  }
}
