import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedMathWidget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedSuper_SkillsTransparent3Widget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedHowisnumber2pronouncedWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedFrameWidget24.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedVector4Widget9.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedFrameWidget25.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedImage1Widget12.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedFrameWidget26.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedFrameWidget23.dart';
import 'package:flutterapp/super_20skillsapp/generatedmath2widget/generated/GeneratedVector3Widget12.dart';

/* Frame Math 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMath2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget10(),
              ),
              Positioned(
                left: 22.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget12(),
              ),
              Positioned(
                left: 22.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget9(),
              ),
              Positioned(
                left: 41.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget23(),
              ),
              Positioned(
                left: 215.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget24(),
              ),
              Positioned(
                left: 41.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget25(),
              ),
              Positioned(
                left: 215.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget26(),
              ),
              Positioned(
                left: 297.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget12(),
              ),
              Positioned(
                left: 70.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 69.0,
                child: GeneratedMathWidget10(),
              ),
              Positioned(
                left: 1.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedHowisnumber2pronouncedWidget(),
              )
            ]),
      ),
    ));
  }
}
