import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector11Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedAvatarWidget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedUser2532Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLevel52Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedUser1123Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/Generated4Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedAvatarWidget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector10Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLevel65Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector3Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/Generated5Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLevel55Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLevel46Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector9Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedAvatarWidget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedMedalgamesvgrepocom1Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedMobileNavItemWidget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedSuper_SkillsTransparent4Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedUser3672Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLevel42Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedTrophysvgrepocom1Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector12Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedAvatarWidget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedAvatarWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedMobileNavItemWidget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/Generated3Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedLeaderboardWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedMobileNavItemWidget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/Generated2Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedUser3455Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedUser2395Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/GeneratedVector8Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedleaderboardwidget/generated/Generated1Widget.dart';

/* Frame Leaderboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeaderboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 85.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 119.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget4()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -121.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget5()),
              ),
              Positioned(
                left: 300.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedTrophysvgrepocom1Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedMedalgamesvgrepocom1Widget1(),
              ),
              Positioned(
                left: 297.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent4Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 0.0,
                child: GeneratedVector8Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 0.0,
                child: GeneratedVector9Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 0.0,
                child: GeneratedVector10Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 0.0,
                child: GeneratedVector11Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 0.0,
                child: GeneratedVector12Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAvatarWidget1(),
              ),
              Positioned(
                left: 61.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAvatarWidget2(),
              ),
              Positioned(
                left: 61.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAvatarWidget3(),
              ),
              Positioned(
                left: 61.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAvatarWidget4(),
              ),
              Positioned(
                left: 61.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAvatarWidget5(),
              ),
              Positioned(
                left: 69.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 69.0,
                child: GeneratedLeaderboardWidget1(),
              ),
              Positioned(
                left: 110.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 49.0,
                child: GeneratedUser2395Widget1(),
              ),
              Positioned(
                left: 110.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 49.0,
                child: GeneratedUser2532Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 49.0,
                child: GeneratedUser3455Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 49.0,
                child: GeneratedUser3672Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 49.0,
                child: GeneratedUser1123Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedLevel65Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedLevel55Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedLevel52Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedLevel46Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 49.0,
                child: GeneratedLevel42Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 52.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 52.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 52.0,
                child: Generated3Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 52.0,
                child: Generated4Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 52.0,
                child: Generated5Widget(),
              )
            ]),
      ),
    ));
  }
}
