import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedFrameWidget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedVector3Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedMobileNavItemWidget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedSuper_SkillsTransparent3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedMobileNavItemWidget11.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedImage1Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedMedalgamesvgrepocom2Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedFrameWidget9.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedFrameWidget8.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedHamburgerMenuWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedMobileNavItemWidget9.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedFrameWidget7.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedPickyoursubjectWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedpickobjectivewidget/generated/GeneratedTrophysvgrepocom2Widget.dart';

/* Frame Pick objective
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPickobjectiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget1(),
              ),
              Positioned(
                left: 299.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 32.842105865478516,
                height: 24.0,
                child: GeneratedHamburgerMenuWidget1(),
              ),
              Positioned(
                left: 12.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget3(),
              ),
              Positioned(
                left: 12.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector4Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget6(),
              ),
              Positioned(
                left: 185.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget7(),
              ),
              Positioned(
                left: 21.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget8(),
              ),
              Positioned(
                left: 185.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedFrameWidget9(),
              ),
              Positioned(
                left: 287.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget3(),
              ),
              Positioned(
                left: 5.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedPickyoursubjectWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 85.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget9()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 119.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget10()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -121.00,
                    y: 375.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget11()),
              ),
              Positioned(
                left: 300.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedTrophysvgrepocom2Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedMedalgamesvgrepocom2Widget(),
              )
            ]),
      ),
    ));
  }
}
