import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedFrameWidget27.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVector5Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVector3Widget13.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedSettings2svgrepocom1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedMedalgamesvgrepocom1Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedMobileNavItemWidget13.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedHamburgerMenuWidget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedLevel32Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedLevel32Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedLogOutWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVector4Widget10.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedParentWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedMobileNavItemWidget12.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVersion10Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedMobileNavItemWidget14.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedTrophysvgrepocom1Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedImage1Widget13.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedSuper_SkillsTransparent3Widget11.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedVector7Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedParentandchildfatherandchildsvgrepocom1Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedAvatarWidget6.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedUser2395Widget2.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedUser2395Widget3.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/super_20skillsapp/generatedhamburgermenuwidget2/generated/GeneratedLogoutsvgrepocom1Widget.dart';

/* Frame Hamburger Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHamburgerMenuWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 225, 85),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedSuper_SkillsTransparent3Widget11(),
              ),
              Positioned(
                left: 299.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 32.842105865478516,
                height: 24.0,
                child: GeneratedHamburgerMenuWidget3(),
              ),
              Positioned(
                left: 12.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 0.0,
                child: GeneratedVector3Widget13(),
              ),
              Positioned(
                left: 0.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 287.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget12()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: 119.00,
                    y: 287.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget13()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 112.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -121.00,
                    y: 287.50,
                    z: 0,
                    child: GeneratedMobileNavItemWidget14()),
              ),
              Positioned(
                left: 287.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedTrophysvgrepocom1Widget3(),
              ),
              Positioned(
                left: 43.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedMedalgamesvgrepocom1Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 150.0,
                child: GeneratedFrameWidget27(),
              ),
              Positioned(
                left: 287.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedImage1Widget13(),
              ),
              Positioned(
                left: 102.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 158.0,
                child: GeneratedAvatarWidget6(),
              ),
              Positioned(
                left: 4.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedUser2395Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 66.0,
                child: GeneratedLevel32Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6555555555555556;

                  final double height = constraints.maxHeight * 1.0015625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.008333333333333333,
                        y: constraints.maxHeight * -0.0015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6972222222222222;

                  final double height = constraints.maxHeight * 1.0125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3638888888888889,
                        y: constraints.maxHeight * -0.0125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle4Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 155.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedSettings2svgrepocom1Widget(),
              ),
              Positioned(
                left: 150.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 49.0,
                child: GeneratedParentandchildfatherandchildsvgrepocom1Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 0.0,
                child: GeneratedVector4Widget10(),
              ),
              Positioned(
                left: 145.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 0.0,
                child: GeneratedVector6Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 0.0,
                child: GeneratedVector7Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 0.0,
                child: GeneratedVector5Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 66.0,
                child: GeneratedLevel32Widget2(),
              ),
              Positioned(
                left: 137.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 69.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 69.0,
                child: GeneratedParentWidget(),
              ),
              Positioned(
                left: 150.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 66.0,
                child: GeneratedLogOutWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 66.0,
                child: GeneratedVersion10Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 66.0,
                child: GeneratedUser2395Widget3(),
              ),
              Positioned(
                left: 160.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedLogoutsvgrepocom1Widget(),
              )
            ]),
      ),
    ));
  }
}
