import 'package:flutter/material.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedImage1Widget7.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedMathWidget5.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedTheansweriscorrectWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedGoodjobWidget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedCorrectsignalsvgrepocom1Widget1.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedVector3Widget7.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedVector4Widget4.dart';
import 'package:flutterapp/super_20skillsapp/generatedmathcorrect3widget/generated/GeneratedSuper_SkillsTransparent3Widget5.dart';

/* Frame Math correct 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMathcorrect3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedMath4Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,

              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 254, 225, 85),
                  ),
                ),
                Positioned(
                  left: 27.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 104.0,
                  height: 104.0,
                  child: GeneratedSuper_SkillsTransparent3Widget5(),
                ),
                Positioned(
                  left: 22.0,
                  top: 144.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector3Widget7(),
                ),
                Positioned(
                  left: 22.0,
                  top: 572.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 0.0,
                  child: GeneratedVector4Widget4(),
                ),
                Positioned(
                  left: 297.0,
                  top: 629.0,
                  right: null,
                  bottom: null,
                  width: 28.0,
                  height: 28.0,
                  child: GeneratedImage1Widget7(),
                ),
                Positioned(
                  left: 70.0,
                  top: 59.0,
                  right: null,
                  bottom: null,
                  width: 362.0,
                  height: 69.0,
                  child: GeneratedMathWidget5(),
                ),
                Positioned(
                  left: 10.0,
                  top: 193.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedTheansweriscorrectWidget1(),
                ),
                Positioned(
                  left: 10.0,
                  top: 313.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 144.0,
                  child: GeneratedGoodjobWidget1(),
                ),
                Positioned(
                  left: 125.0,
                  top: 403.0,
                  right: null,
                  bottom: null,
                  width: 137.0,
                  height: 137.0,
                  child: GeneratedCorrectsignalsvgrepocom1Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
